### ISSUE TITLE
Coc-lua break with new language server

### ISSUE THREAD

**Issue by Maswor** [josa42/coc-lua#71] opened 2021-07-03 07:16 UTC
When prompted for updating new version of lua language server, I processed and get the following errors:

[coc.nvim] [14:13:56.486][error][#0:script/library.lua:233]: script/library.lua:197: attempt to call a nil value (field 'get')
[coc.nvim] Server lua failed to start: Error: [14:13:56.486][error][#0:script/library.lua:233]: script/library.lua:197: attempt to call a nil value (field 'get')

cos-lua: 1.0.1
neovim: 0.5 stable

Thank you and best regards!

**Comment by numToStr** [comment] 2021-07-03 13:13
The same is happening with me.

**Comment by lc9er** [comment] 2021-07-04 01:20
Same here. Installed neovim 0.5, was prompted to run CocCommand lua.update. That failed. I uninstalled and resinstalled coc-lua and get the following:

```
[coc.nvim] [21:17:06.230][error][#0:script\library.lua:233]: script\library.lua:197: attempt to call a nil value (field 'get')
stack traceback:
        script\library.lua:233: in upvalue 'initFromMetaDoc'
        script\library.lua:237: in upvalue 'init'
        script\library.lua:241: in function 'library.init'
        script\provider\provider.lua:82: in function <script\provider\provider.lua:80>
        [C]: in function 'xpcall'
[coc.nvim] Server lua failed to start: Error: [21:17:06.230][error][#0:script\library.lua:233]: script\library.lua:197: attempt to call a nil value (field 'get')
```

**Comment by cjnucette** [comment] 2021-07-05 11:47
I've got the same problem. As a workaround I did the following: first, I did a `rm -rf sumneko-lua-ls` in `~/.config/coc/extensions/coc-lua-data/`, next I downloaded an previous version (`2.0.5` in  my case) from <https://github.com/josa42/coc-lua-binaries/releases>, then extracted it, and finally renamed it as `sumneko-lua-ls`. See [#65](https://github.com/josa42/coc-lua/issues/65) for clarification.
I hope this helps.

**Comment by lc9er** [comment] 2021-07-05 17:14
> 
> 
> I've got the same problem. As a workaround I did the following: first, I did a `rm -rf sumneko-lua-ls` in `~/.config/coc/extensions/coc-lua-data/`, next I downloaded an previous version (`2.0.5` in my case) from https://github.com/josa42/coc-lua-binaries/releases, then extracted it, and finally renamed it as `sumneko-lua-ls`. See [#65](https://github.com/josa42/coc-lua/issues/65) for clarification.
> I hope this helps.

This worked perfectly. Thank you!

Note for Windows users, the path to the coc-lua-data dir is slightly different. You'll probably find the directory here: ~\AppData\Local\coc\extensions\coc-lua-data.

**Comment by oblitum** [comment] 2021-07-06 20:59
Yep, this is actually a duplicate of #65. coc-lua just doesn't update coc-lua-binaries, if you scrap it and its coc-lua-data directory, it works fine.

**Comment by poetaman** [comment] 2021-07-07 00:47
Same problem here!

**Comment by oblitum** [comment] 2021-07-07 12:09
There's 5 issues currently open, 4 of them are about this update thing.

**Comment by oblitum** [comment] 2021-08-01 00:20
I highly recommend [coc-sumneko-lua](https://github.com/xiyaowong/coc-sumneko-lua) over coc-lua, which currently is not being actively maintained.

**Closed as completed** 2023-02-18 22:55 UTC
